services:
  mnist:
    build: .
    devices:
    - /dev/nvidia0
    - /dev/nvidia1
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    image: tensorflow/tensorflow:latest-gpu
    ports:
    - 8888:8888
    - 9999:9999
    volumes:
    - .:/mnist
    - /mnt/data:/mnt/data
    - /tmp/.X11-unix:/tmp/.X11-unix
    - /etc/localtime:/etc/localtime:ro
    - nvidia_driver_384.111:/usr/local/nvidia:ro
version: '2'
volumes:
  nvidia_driver_384.111:
    external: true
